OJ-2320: added alarms for the dead Letter event queue and the audit e…
govuk-one-login/ipv-cri-common-infrastructure pull request #97
Opened 2024-06-26 12:42 UTC by liamStockwellGDS

…vent queue

NINO | Platform | Add alarms for AuditQueue and Dead Letter Queue

Proposed changes
What changed
added alarms to template file.

Why did it change
To allow for alarms

Issue tracking
[OJ-2320](https://govukverify.atlassian.net/browse/OJ-2320)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

[OJ-2320]: https://govukverify.atlassian.net/browse/OJ-2320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-26 13:09 UTC, Caitlin-cooling commented on txma/template.yaml
> +      AlarmDescription: !Sub "Trigger an alarm when the age of the oldest audit event message is 5 or more minutes. ${SupportManualURL}"
Where is this `SupportManualURL` defined?

2024-06-26 13:10 UTC, Caitlin-cooling commented on txma/template.yaml
> +        - !ImportValue platform-alarm-topic-slack-warning-alert
This value looks a bit different to the AlarmActions we have in NINo - is there a reason for this?

2024-06-26 13:12 UTC, surajkumar requested changes

2024-06-26 13:12 UTC, surajkumar commented on txma/template.yaml
> +      AlarmDescription: !Sub "Trigger an alarm when the age of the oldest audit event message is 5 or more minutes. ${SupportManualURL}"
Maybe rename this to be more clear e.g.  "Alarm for when a message has stayed on the queue for more than 5 minutes", similarly with the resource name

2024-06-26 13:12 UTC, surajkumar commented on txma/template.yaml
> +    Condition: "DeployAlarms"
This condition does not exist so the template will fail to deploy. Could you please add the condition, remove the `"` and make sure you have tested the alarm.

2024-06-26 13:12 UTC, surajkumar commented on txma/template.yaml
> +  AuditEventDLQMessagesVisibleAlarm:
Could anything from the answers on SO be helpful here? https://stackoverflow.com/questions/60211243/configure-sqs-dead-letter-queue-to-raise-a-cloud-watch-alarm-on-receiving-a-mess

2024-07-01 16:21 UTC, surajkumar requested changes

2024-07-01 16:25 UTC, Caitlin-cooling commented on txma/template.yaml
> +    Default: "none"
Think we can revert this back now

2024-07-01 16:26 UTC, Caitlin-cooling commented on txma/template.yaml
> +  TxmaStackName:
Sorry what do we need this for? We're in the txma stack no? 🤔

2024-07-01 16:27 UTC, Caitlin-cooling commented on txma/template.yaml
> -    Condition: IsNotDevEnvironment
Think @CharlesIC put these in for a reason - is there a reason you're taking them out?

2024-07-01 16:28 UTC, Caitlin-cooling commented on txma/template.yaml
> +      Name:  !Sub ${AWS::StackName}-AuditEventQueueNameToRemove
I know this is needed for local dev but we are sure that nothing is importing using the old name?

2024-07-01 17:20 UTC, CharlesIC approved these changes

2024-07-01 17:21 UTC, CharlesIC commented on txma/template.yaml
> +      Name: !Sub ${AWS::StackName}-AuditEventDLQArn
```suggestion
      Name: !Sub ${AWS::StackName}-AuditEventDLQArn
      
```
Restore the newline at the end of the file

2024-07-02 08:51 UTC, surajkumar approved these changes

2024-07-02 08:57 UTC, merged